version: 2

defaults: &defaults
  docker:
    - image: circleci/node:latest-browsers
  environment:
    NODE_OPTIONS: --max_old_space_size=4096
    # NPM_CONFIG_LOGLEVEL: error
    JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed
  working_directory: ~/gatsby-blog

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
      - run: yarn lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
      - run: yarn test --runInBand --no-cache
      - run: yarn test:coverage --runInBand --no-cache
      - run: yarn global add codecov
      - run: yarn codecov

  # coverage:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - node-modules-{{ checksum "package.json" }}
  #     - run: yarn test:coverage --runInBand --no-cache
  #     - save_cache:
  #         key: coverage-{{ .Environment.CIRCLE_SHA1 }}
  #         paths:
  #           - coverage
  # codecov:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - node-modules-{{ checksum "package.json" }}
  #     - restore_cache:
  #         keys:
  #           - coverage-output-{{ .Environment.CIRCLE_SHA1 }}
  #     - run: yarn global add codecov
  #     - run: yarn codecov

workflows:
  version: 2
  test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      # - coverage:
      #     requires:
      #       - install
      # - codecov:
      #     requires:
      #       - coverage
