name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [11.x, 12.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
      - run: yarn test:coverage --runInBand --no-cache
        env:
          CI: true
          HEADLESS: false
          TEST_TIMEOUT: 300000
          PROGRESS: none
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
